# Generated by Django 4.2.7 on 2023-11-19 19:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_subscription'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Subscription',
        ),
    ]
