# Generated by Django 5.0 on 2024-01-03 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_profile_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_locked',
            field=models.BooleanField(default=False),
        ),
    ]
