# Generated by Django 4.2.7 on 2023-11-20 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_profile_following'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact',
            options={'ordering': ['-created']},
        ),
    ]
