# Generated by Django 4.2.6 on 2023-12-15 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_profile_bio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='bio',
        ),
    ]
