# Generated by Django 5.0 on 2023-12-20 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_activeuser_alter_profile_following'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='disable_chat',
            field=models.BooleanField(default=False),
        ),
    ]
