# Generated by Django 5.0 on 2023-12-23 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_profile_disable_chat'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='bio',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='user_type',
            field=models.CharField(choices=[('BG', 'Bloger'), ('SE', 'Software engineering'), ('GD', 'Graphic designer'), ('FP', 'Football player'), ('MS', 'Musician'), ('SM', 'SMM manager'), ('MA', 'Marketology')], default='BG', max_length=100),
        ),
    ]
