# Generated by Django 5.0 on 2023-12-23 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0011_profile_bio_profile_user_type'),
        ('original', '0014_savedpost'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='saved_posts',
            field=models.ManyToManyField(related_name='saved_by', to='original.post'),
        ),
    ]
