# Generated by Django 5.0 on 2023-12-25 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0012_profile_saved_posts'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user_type',
            field=models.CharField(choices=[('Bloger', 'Bloger'), ('Software engineering', 'Software Engineering'), ('Graphic designer', 'Graphic Designer'), ('Football player', 'Football Player'), ('Musician', 'Musician'), ('SMM manager', 'Smm Manager'), ('Marketology', 'Marketology')], default='Bloger', max_length=100),
        ),
    ]
