# Generated by Django 5.0 on 2023-12-28 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0013_profile_location_alter_profile_user_type'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ActiveUser',
        ),
    ]
