# Generated by Django 5.0 on 2023-12-29 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0018_profile_is_online'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='is_online',
        ),
    ]
