# Generated by Django 4.2.7 on 2023-11-08 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('original', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='images',
            field=models.ImageField(default=1, upload_to='original/post/images'),
            preserve_default=False,
        ),
    ]
