# Generated by Django 5.0.1 on 2024-01-26 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('original', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='sign',
            field=models.ImageField(blank=True, null=True, upload_to='media/symbol/images/'),
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media/posts/images/'),
        ),
        migrations.AlterField(
            model_name='post',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='media/posts/videos/'),
        ),
    ]
