# Generated by Django 4.2.7 on 2023-11-08 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('original', '0002_post_images'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='email',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='name',
        ),
    ]
