# Generated by Django 4.2.7 on 2023-11-08 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('original', '0004_comment_email_comment_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='email',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='name',
        ),
    ]
