# Generated by Django 4.2.7 on 2023-11-09 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('original', '0005_remove_comment_email_remove_comment_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='body',
        ),
        migrations.AddField(
            model_name='comment',
            name='text',
            field=models.CharField(default=1, max_length=2000),
            preserve_default=False,
        ),
    ]
