# Generated by Django 4.2.7 on 2023-11-10 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('original', '0007_remove_comment_text_comment_body'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='status',
        ),
    ]
