# Generated by Django 4.2.7 on 2023-11-19 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('original', '0010_post_views'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='views',
        ),
        migrations.AddField(
            model_name='post',
            name='hashtag',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
