# Generated by Django 5.0 on 2023-12-23 14:24

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('original', '0017_post_hidden_delete_hiddenpost'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='slug',
            field=models.SlugField(default=uuid.uuid1),
        ),
    ]
