# Generated by Django 5.0 on 2023-12-24 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('original', '0019_remove_post_hidden_hiddenpost'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='hidden',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='HiddenPost',
        ),
    ]
