# Generated by Django 5.0 on 2023-12-25 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('original', '0020_post_hidden_delete_hiddenpost'),
    ]

    operations = [
        migrations.CreateModel(
            name='HashTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='post',
            name='hashtag',
        ),
        migrations.AddField(
            model_name='post',
            name='hashtags',
            field=models.ManyToManyField(blank=True, related_name='posts', to='original.hashtag'),
        ),
    ]
