# Generated by Django 5.0 on 2023-12-25 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('original', '0021_hashtag_remove_post_hashtag_post_hashtags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=models.SlugField(max_length=200, unique=True),
        ),
    ]
