# Generated by Django 5.0 on 2023-12-29 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('original', '0023_post_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='hashtags',
        ),
        migrations.DeleteModel(
            name='HashTag',
        ),
        migrations.AddField(
            model_name='post',
            name='hashtags',
            field=models.CharField(default=1, max_length=500),
            preserve_default=False,
        ),
    ]
