# Generated by Django 5.0 on 2023-12-31 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('original', '0024_remove_post_hashtags_delete_hashtag_post_hashtags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
