# Generated by Django 5.0 on 2023-12-20 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_messagemodel_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='messagemodel',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='uploaded_images/'),
        ),
    ]
